Project3
sergiocortessat/Week3---NewsWeek-Bootstrap pull request #1
Opened 2021-01-25 15:38 UTC by mgunduz1

Milestone 1 completed.

2021-01-25 17:23 UTC, uryelah commented
## Invalid Pull Request 🛑 

I'm sorry to inform I'll have to make you submission as **Invalid** for the following reasons:

1. The Pull Request does not have a relevant description that describes well enough the features achieved in this milestone.

Please review the [Professional GitHub repository lesson](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) and update your  PR message according to the models/links under the lesson *3 basic rules to follow in Microverse projects*.

![pr_message](https://user-images.githubusercontent.com/16193212/105741281-dd34a200-5f18-11eb-93c3-dd3c5f36d0f9.gif)


When the fixes are made please re-submit the review for Milestone 1.

2021-01-25 17:48 UTC, sergiocortessat commented
Newsweek clone project. We have added the requested Navbar and Footer for milestones one. It includes the logos, icons, colors, and complies with responsiveness for phone, tablet and desktop sizes.

2021-01-25 20:39 UTC, Spayco approved these changes
# Milestone Approved ✔️ 

Milestone approved, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.

- [x] you forgot to make some of the elements as links, this includes the logo, Login, Subscribe, footer links, and Social media Icons ([Link to page](https://www.newsweek.com/))


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-26 16:57 UTC, sergiocortessat commented
Milestone 2 delivery. We have added the middle section that includes 3 columns. We have added the responsive design for the 3 devices and taken care of the order while resizing.

2021-01-26 21:19 UTC, Spayco approved these changes
# Milestone Approved ✔️ 

Milestone approved, great work on managing to build the webpage without using custom CSS, however, there are things that you need to change, you can either make the changes now, or you keep them to the last milestone.



**Desktop**
- [x] you're missing the **LATEST NEWS** section in the middle column under the **MORE STORIES** section

**Tablet**
- [x] you're missing the **LATEST NEWS** section in the right column under the **MORE STORIES** section

**Mobile**

- [x] you're missing the **LATEST NEWS** section under the **MORE STORIES** section
- [ ] there are more **SPONSORED INSIGHT** after the Sign Up section.

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-26 21:19 UTC, Spayco commented on index.html
> +<section style="font-family: Arial, Helvetica, sans-serif;"
- [ ] Please don't include inline stylings, instead put all of this in the CSS file.

2021-01-26 21:19 UTC, Spayco commented on index.html
> +<footer style="font-family: Arial, Helvetica, sans-serif;" class="pt-5 bg-white row">
- [ ] Please don't include inline stylings, instead put all of this in the CSS file.

2021-01-27 15:10 UTC, mgunduz1 commented
LATEST NEWS and SPONSORED INSIGHT parts added from the last milestone.

All the requirements for milestone 3 added with responsive design approach.

This is the final version of our bootstrap project.

2021-01-27 20:28 UTC, uryelah requested changes
Hi **Mert Gündüz** & **Sergio Cortes Satizabal** , I'm Sarah your reviewer for this PR 👩‍🚀 

You guys did an great job in this milestone! You did specially great in the main section scroll behavior and going beyond what was asking by adding the little favicon 'N' icon to the head of your clone.

There are still some points to work on before finishing this project so just check my feedback carefully, **make the required changes, and then request a re-review for this milestone**!

Remember sure to use the same PR, and to check the requests inside and under this message very carefully 😉 

You are really close so keep on coding and Rock on! 🎸 👨‍🎤 

# Required Changes 🏗️ 🐛 💡

-----

 **Kindly fix the pointed out items and comments below, then start working on the next milestone**
 
- [ ] Each article image should also be a link, the same way the titles are. The user of the NewsWeek site is able to click an image and be linked to the article, so make sure there are links around each article image.

---

- [ ] Make sure that in the places you use the square Newsweek 'N' logo the logo is not distorted, it should be square and not a thin rectangle.
See how in the screenshots below the 'N' is distorted:

![Screenshot_2021-01-27 Newsweek(2)](https://user-images.githubusercontent.com/16193212/106048382-92a35900-60c3-11eb-85f2-55ca65c3e2b0.png)
![Screenshot_2021-01-27 Newsweek(5)](https://user-images.githubusercontent.com/16193212/106048330-83bca680-60c3-11eb-90e5-08c4ff84f7ab.png)

*How it should be:*
![Screenshot_2021-01-27 Newsweek(1)](https://user-images.githubusercontent.com/16193212/106048379-920ac280-60c3-11eb-8a6f-309dacae0f70.png)

---

- [x] Let's make sure the background, the sides of the screen, in the desktop size is the same grey the original site uses instead of just white. Careful to make sure that doesn't show up on the tablet and mobile sizes.

Note how in the screenshot from the original site below you can see the left and right margins of the site with that grey color:
![Screenshot_2021-01-27 Newsweek(4)](https://user-images.githubusercontent.com/16193212/106048680-f4fc5980-60c3-11eb-9775-724c9d4f27eb.png)

----

- [x] Make sure  that you are **using the correct shade of red in your clone**, using Bootstrap well is great! But sadly the Bootstrap red is not the same as the Newsweek brand red.

Go over all the places you are using the incorrect shade of red and modify it so it matches the original one.

---

- [ ] [OPTIONAL] If you want to be even more semantic, use the `article` tag for each article inside your clone sections. Read more on the [article tag here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article).

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-01-27 20:28 UTC, uryelah commented on index.html
> +      <h6 class="red text-danger">NEWSLETTER</h6>
- [ ] Make sure that this title has the correct font-weight. 
This, 'Subscribe', ' Featured Stories', 'Top Story', 'The Debate', and 'Opinion' in special also have the same issue of having a too low font-weight.

Compare your clone and the original archived site and make sure the text styles match.

2021-01-27 20:28 UTC, uryelah commented on index.html
> +      <h6 class="red text-danger">NEWSLETTER</h6>
- [ ] Spend more time on the responsiveness of the 'Subscribe' section text on the tablet size:
**Your version**
![Screenshot_2021-01-27 Newsweek(3)](https://user-images.githubusercontent.com/16193212/106048676-f3cb2c80-60c3-11eb-9efb-832621411ddf.png)
**Original version**
![subscribe_and_newsletter_tablet](https://user-images.githubusercontent.com/16193212/106049307-c29f2c00-60c4-11eb-9813-26bff4cd6786.png)

---

- [ ] Spend more time on the responsiveness of the 'Newsletter' section image on the mobile size:
**Your version**
![Screenshot_2021-01-27 Newsweek](https://user-images.githubusercontent.com/16193212/106048684-f594f000-60c3-11eb-8577-c7a0261110b3.png)
**Original version**
![subscribe_and_newsletter_mobile](https://user-images.githubusercontent.com/16193212/106049277-b87d2d80-60c4-11eb-9918-5c2638d1263c.png)

2021-01-28 09:35 UTC, sergiocortessat commented
Milestone 3: TSE changes requested. Newsletter margins, logo margins, Red color, General margins, Bold titles.

2021-01-28 16:31 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] You still need to fix the Subscribe / Newsletter section problems mentioned by the previous TSE

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2021-01-28 17:20 UTC, mgunduz1 commented
> # Changes Requested
> Hello Team! 
> Awesome job so far!!  you still need to make some changes though!
> 
> ## Required Changes 
> * [ ]  You still need to fix the Subscribe / Newsletter section problems mentioned by the previous TSE
> 
> ### please make the appropriate changes and ask for another code review 
> Happy Coding!
> 
> Best,
> Aziz Mejri
> _contact me on [twitter](https://twitter.com/iSpaYco) or slack (@Spayco) if you need any help_

Hi Aziz, We already did the changes that requested. So we can't understand what you meant with **"You still need to fix the Subscribe / Newsletter section problems mentioned by the previous TSE"**. 

![Screenshot_1](https://user-images.githubusercontent.com/74907327/106174423-146bb300-61a6-11eb-9f8b-fb0e22b9abfb.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/74907327/106174428-159ce000-61a6-11eb-8611-677da08ed1b8.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/74907327/106174432-16357680-61a6-11eb-8f59-a1525e508eca.jpg)

( CURRENT VERSİON OF OUR PROJECT)

2021-01-28 17:28 UTC, Spayco commented
hey @mgunduz1, for the subscribe section, it break on 650px width 
![image](https://user-images.githubusercontent.com/11758151/106175482-77ede480-6196-11eb-8cfd-4a77789f786f.png)

and the newsletter, the section where it has text and form should be centered

2021-01-28 20:40 UTC, sergiocortessat commented
Adding TSE changes request for fix the Subscribe / Newsletter section. We have added the proper format for the screen sizes. Mobile and tablet maintain on the row (email + signup button) and Desktop switch a column style. Thanks

2021-01-29 09:46 UTC, uryelah approved these changes
Hi **Mert Gündüz & Sergio Cortes Satizabal**, I'm Sarah your reviewer for this PR 👩‍🚀 

You did a great job updating your project according to the change requests , good work specially with that last pesky one!

Good luck with your HTML&CSS Capstones! 🚀  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---------

### For your next projects
- [ ] Make sure your next commits follow the best committing formatting practices.
They should all be written in the imperative present mood and be capitalized:
```
// Good
Add first commit

// Bad
adding first commit
```

---------

    
    
**Keep being awesome devs and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-01-29 10:06 UTC, merged